version: "3.9"
services:
  mock-server:
    environment:
      - API_VERSION=1.0
    build:
      context: ../
      dockerfile: Docker/mock-server/Dockerfile
    volumes:
      - ../mock-server/db.json:/app/mock-server/db.json
      - ../.env:/app/.env
    ports:
      - "5050:5050"

  prod-server-local-db:
    env_file:
      - ../.env
    environment:
      - API_VERSION=1.0
      - USE_CLOUD_DB=false
      - PROD_PORT=4000
      - MONGODB_URI_LOCAL=mongodb://mongodb:27017/TabcolabDB
    build:
      context: ../
      dockerfile: Docker/prod-server/Dockerfile
    volumes:
      - ../.env:/app/.env
    ports:
      - "4000:4000"
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../prod-server/mongodb_data:/data/db

  prod-server-cloud-db:
    env_file:
      - ../.env
    environment:
      - API_VERSION=1.0
      - USE_CLOUD_DB=true
      - PROD_PORT=5000
      - MONGODB_URI_LOCAL=mongodb://mongodb:27017/TabcolabDB
    build:
      context: ../
      dockerfile: Docker/prod-server/Dockerfile
    volumes:
      - ../.env:/app/.env
    ports:
      - "5000:5000"
