version: "3.9"
services:

  prod-server-cloud-db:
    env_file:
      - ../.env
    environment:
      - API_VERSION=1.0
      - USE_CLOUD_DB=true
      - PROD_PORT=5000
      - MONGODB_URI_LOCAL=mongodb://mongodb:27017/TabcolabDB
    build:
      context: ../
      dockerfile: Docker/prod-server/Dockerfile
    volumes:
      - ../.env:/app/.env
    ports:
      - "5000:5000"
      
  nginx:
    environment:
      - SERVER_NAME=13.115.132.26
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - prod-server-cloud-db
      # - prod-server-local-db
      # - mongodb
      
  # prod-server-local-db:
  #   env_file:
  #     - ../.env
  #   environment:
  #     - API_VERSION=1.0
  #     - USE_CLOUD_DB=false
  #     - PROD_PORT=4000
  #     - MONGODB_URI_LOCAL=mongodb://mongodb:27017/TabcolabDB
  #   build:
  #     context: ../
  #     dockerfile: Docker/prod-server/Dockerfile
  #   volumes:
  #     - ../.env:/app/.env
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - mongodb

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ../prod-server/mongodb_data:/data/db
  #   privileged: true