version: "3.9"
services:

  server-cloud-db:
    env_file:
      - ../.env
    environment:
      - API_VERSION=1.0
      - USE_CLOUD_DB=true
      - PORT=5000
    build:
      context: ../
      dockerfile: Docker/server/Dockerfile
    volumes:
      - ../.env:/app/.env
    ports:
      - "5000:5000"
      
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server-cloud-db
      # - server-local-db
      # - mongodb
      
  # server-local-db:
  #   env_file:
  #     - ../.env
  #   environment:
  #     - API_VERSION=1.0
  #     - USE_CLOUD_DB=false
  #     - PORT=4000
  #   build:
  #     context: ../
  #     dockerfile: Docker/server/Dockerfile
  #   volumes:
  #     - ../.env:/app/.env
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - mongodb

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ../server/mongodb_data:/data/db
  #   privileged: true