name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      API_VERSION: ${{ secrets.API_VERSION }}
      PASSPORT_SECRET: ${{ secrets.PASSPORT_SECRET }}
      USE_CLOUD_DB: ${{ secrets.USE_CLOUD_DB }}
      PROD_PORT: ${{ secrets.PROD_PORT }}
      DEV_PORT: ${{ secrets.DEV_PORT }}
      MONGODB_URI_LOCAL: ${{ secrets.MONGODB_URI_LOCAL }}
      MONGODB_URI_CLOUD: ${{ secrets.MONGODB_URI_CLOUD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_AUTH_CALLBACK_URL: ${{ secrets.GOOGLE_AUTH_CALLBACK_URL }}
      CLOUD_GITHUB_CLIENT_ID: ${{ secrets.CLOUD_GITHUB_CLIENT_ID }}
      CLOUD_GITHUB_CLIENT_SECRET: ${{ secrets.CLOUD_GITHUB_CLIENT_SECRET }}
      CLOUD_GITHUB_AUTH_CALLBACK_URL: ${{ secrets.CLOUD_GITHUB_AUTH_CALLBACK_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Ipv4 address of EC2 instance
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }} # Add public key to EC2 instance and private key to Github secrets
          envs: API_VERSION,PASSPORT_SECRET,USE_CLOUD_DB,PROD_PORT,DEV_PORT,MONGODB_URI_LOCAL,MONGODB_URI_CLOUD,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_AUTH_CALLBACK_URL,SESSION_SECRET,CLOUD_GITHUB_CLIENT_ID,CLOUD_GITHUB_CLIENT_SECRET,CLOUD_GITHUB_AUTH_CALLBACK_URL
          script: |
            if [ ! -d "tabcolab" ]; then 
              git clone -b feature/api-refactor git@github.com:SideProjectAC/tabcolab.git
              cd tabcolab
            else
              cd tabcolab
              git pull origin feature/api-refactor
            fi
            echo API_VERSION=$API_VERSION > .env
            echo PASSPORT_SECRET=$PASSPORT_SECRET >> .env
            echo USE_CLOUD_DB=$USE_CLOUD_DB >> .env
            echo PROD_PORT=$PROD_PORT >> .env
            echo DEV_PORT=$DEV_PORT >> .env
            echo MONGODB_URI_LOCAL=$MONGODB_URI_LOCAL >> .env
            echo MONGODB_URI_CLOUD=$MONGODB_URI_CLOUD >> .env
            echo GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID >> .env
            echo GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET >> .env
            echo GOOGLE_AUTH_CALLBACK_URL=$GOOGLE_AUTH_CALLBACK_URL >> .env
            echo CLOUD_GITHUB_CLIENT_ID=$CLOUD_GITHUB_CLIENT_ID >> .env
            echo CLOUD_GITHUB_CLIENT_SECRET=$CLOUD_GITHUB_CLIENT_SECRET >> .env
            echo CLOUD_GITHUB_AUTH_CALLBACK_URL=$CLOUD_GITHUB_AUTH_CALLBACK_URL >> .env
            echo SESSION_SECRET=$SESSION_SECRET >> .env
            sudo chmod 600 .env
            sudo chown -R $USER /home/***/tabcolab/prod-server/mongodb_data
            cd Docker
            sudo docker system prune -a -f
            docker-compose down --rmi all
            docker-compose up --build -d
